version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: shixiaoya-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: shixiaoya_db
      MYSQL_USER: shixiaoya
      MYSQL_PASSWORD: shixiaoya123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: shixiaoya-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 后端API服务
  api:
    build: .
    container_name: shixiaoya-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: shixiaoya_db
      DB_USER: shixiaoya
      DB_PASSWORD: shixiaoya123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: shixiaoya_jwt_secret_key_2024_production
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data: